# Generated by Django 4.1.2 on 2022-11-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_alter_artiste_age_alter_lyric_song_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyric',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='date_released',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='likes',
            field=models.CharField(max_length=100000000),
        ),
    ]
